# Site settings
title: Куето - моят приятел
email: toni.dushkov@gmail.com
description: "„Кучето е единственото нещо на земята, което те обича повече от себе си.“"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: tonydushkov
github_username:  dushkov

# Build settings
markdown: kramdown
permalink: pretty
